import { aeKernel } from "../../Kernel/AEKernel.js";
import { AutoTestShell } from "../../Models/AutoTestShell.js";
import { mediaTypes } from "../../Utils/aeUtils.js";

/**
 * Jira: https://ssbbart.atlassian.net/browse/ENG-1113
 * @returns {AutoTestShell} testShell
 */
export function test1113() {
	aeKernel.addGuidedAutomaticTest("1113", {
		bestPractice: 602,
		testId: 1113,
		introduced: "2.21",
		mediaType: mediaTypes.WEB,
		description: "One or more Custom elements with a tabindex set to 0 or a positive value, excluding those elements with aria-hidden='true', not intentionally hidden in the DOM, lacks a role attribute.",
		metaText: "This element is focusable but lacks a role attribute.",
		metaTextDetail: "This {{tag-name}} is focusable but lacks a role attribute.",
		fixType: "",
		testFunc: function () {
			//Anything not on this list is a custom element - 122 standard elements as of 1/14/2022
			//See https://developer.mozilla.org/en-US/docs/Web/HTML/Element
			//Excludes most deprecated elements. Hopefully nobody is using a "spacer" element make an interactive custom control
			const tags = [
				'html',
				'head',
				'title',
				'base',
				'link',
				'meta',
				'style',
				'body',
				'article',
				'section',
				'nav',
				'aside',
				'h1',
				'h2',
				'h3',
				'h4',
				'h5',
				'h6',
				'hgroup',
				'header',
				'footer',
				'address',
				'p',
				'hr',
				'pre',
				'blockquote',
				'ol',
				'ul',
				'li',
				'dl',
				'dt',
				'dd',
				'figure',
				'figcaption',
				'div',
				'main',
				'a',
				'em',
				'strong',
				'small',
				's',
				'cite',
				'q',
				'dfn',
				'abbr',
				'data',
				'time',
				'code',
				'var',
				'samp',
				'kbd',
				'sub',
				'sup',
				'i',
				'b',
				'u',
				'mark',
				'ruby',
				'rb',
				'rt',
				'rtc',
				'rp',
				'bdi',
				'bdo',
				'span',
				'br',
				'wbr',
				'ins',
				'del',
				'picture',
				'img',
				'iframe',
				'embed',
				'object',
				'param',
				'video',
				'audio',
				'source',
				'track',
				'map',
				'area',
				'math',
				'svg',
				'table',
				'caption',
				'colgroup',
				'col',
				'tbody',
				'thead',
				'tfoot',
				'tr',
				'td',
				'th',
				'form',
				'label',
				'input',
				'button',
				'select',
				'datalist',
				'optgroup',
				'option',
				'textarea',
				'keygen',
				'output',
				'progress',
				'meter',
				'fieldset',
				'legend',
				'script',
				'noscript',
				'template',
				'canvas',
				'rect',
				'g',
				'path',
				'circle',
				'details',
				'summary',
				'dialog',
				'slot',
				'portal',
				'menu',
			];

			const customElementCssSelector = tags.map(tagName => `:not(${tagName})`).join('');
			const baseCssSelector = `*[tabindex]:not([tabindex=""]):not([tabindex^="-"]):not([aria-hidden="true"])[data-ae_vis]${customElementCssSelector}`;
			return new AutoTestShell(
				baseCssSelector,
				`${baseCssSelector}[data-ae_ar="null"]`
			);
		}
	});
}
